# only builds and tests on tag pushes and PRs to master
# only pushes on tag pushes
name: build, test, publish
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '.gitignore'
      - 'docker-compose.yml'
      - 'LICENSE'
      - '**.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '.gitignore'
      - 'docker-compose.yml'
      - 'LICENSE'
      - '**.md'

jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Extract tag name
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: vroomvrp/vroom-docker
          tags: type=semver,pattern=v{{raw}}

      - name: Build Image
        run: |
          echo "Building image ${{ steps.meta.outputs.tags }}"
          docker build -t ${{ steps.meta.outputs.tags }} .

      - name: Test image
        run : sudo /bin/bash -c "./tests/test.sh ${{ steps.meta.outputs.tags }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

      # only push on tags, not on pull_request
      - name: Push image
        run: docker push ${{ steps.meta.outputs.tags }}
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')