# only builds and tests on master pushes
name: Master push
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.gitignore'
      - 'docker-compose.yml'
      - 'LICENSE'
      - '**.md'

jobs:
  build_test_publish:
    strategy:
        matrix:
          platform: [linux/arm64, linux/amd64]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        run: |
          echo "Building image vroomvrp/vroom-docker:latest"
          docker buildx build --load --platform ${{ matrix.platform }} --tag vroomvrp/vroom-docker:latest .

      - name: Test tagged image
        run : |
          sudo /bin/bash -c "./tests/test.sh vroomvrp/vroom-docker:latest"      
